import type { Metadata } from "next";
import Header from "../components/Header/Header";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import { Noto_Color_Emoji } from 'next/font/google';

const notoEmoji = Noto_Color_Emoji({
    subsets: ['emoji'], 
    weight: ['400'], 
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <script src="https://kit.fontawesome.com/44ddc9fabc.js" crossOrigin="anonymous" async />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          rel="stylesheet"
        />
      </head>
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
