import type { Metadata } from "next";
import Header from "../components/Header/Header";
import "./globals.css";
import { Noto_Color_Emoji } from 'next/font/google';

const notoEmoji = Noto_Color_Emoji({
    subsets: ['emoji'], 
    weight: ['400'], 
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
